# Generated by Django 5.0.2 on 2024-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_add",
            field=models.DateField(),
        ),
    ]
