# Generated by Django 5.0.2 on 2024-03-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0003_remove_order_client_alter_order_order_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="all_price",
            new_name="product_price",
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(),
        ),
    ]
